openapi: 3.0.3
info:
  title: Projeto de Gestão de Montagem de Drones
  description: >-
    Desenvolver uma aplicação web para gerir o processo de montagem de drones. A
    aplicação deve permitir aos utilizadores registar-se, autenticar-se e criar,
    visualizar, atualizar e eliminar informações relacionadas com a montagem de
    drones. Os endpoints da API devem ser implementados de acordo com as
    melhores práticas RESTful. Os endpoints deverão ser documentados em OpenAPI.
  version: 1.0.1
tags:
  - name: auth
    description: Autenticação dos utilizadores
  - name: drone
    description: Tudo sobre os seus drones
  - name: pecas
    description: Tudo sobre as peças dos drones
  - name: user
    description: Operações dos utilizadores
paths:
  
      
  /user:
    post:
      tags:
        - user
      summary: Cria um utilizador
      description: Isto só consegue ser feito pelo sign up.
      operationId: createUser
      requestBody:
        description: Criado utilizador.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/xml:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        default:
          description: operação bem sucedida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
            application/xml:
              schema:
                $ref: '#/components/schemas/User'
                
  /login:
    post:
      tags:
        - auth
      summary: Cria uma sessão autenticada
      parameters:
        - in: query
          name: user
          description: The user to create.
          schema:
            type: object
            required:
              - userName
            properties:
              username:
                type: string
              password:
                type: string
      responses:
        '200':
          description: Token do utilizador autenticado
        '404':
          description: Utilizador ou senha invalidos

            
  /user/{userId}:
    get:
      tags:
        - user
      summary: Encontrar utilizador pelo seu Id
      description: ''
      operationId: getUserById
      parameters:
        - name: userId
          in: path
          description: O Id que precisa de ser encontrado.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: operação bem sucedida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
            application/xml:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalido Id fornecido
        '404':
          description: Utilizador não encontrado
    patch:
      tags:
        - user
      summary: Atualizar utilizador
      description: Isto só pode ser feito por um utilizador logado.
      operationId: updateUser
      parameters:
        - name: userId
          in: path
          description: Id que precisa de ser alterado
          required: true
          schema:
            type: string
      requestBody:
        description: Atualizar utilizador existente
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/xml:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        default:
          description: operação bem sucedida
    delete:
      tags:
        - user
      summary: Apagar utilizador
      description: Isto só pode ser feito por um utilizador logado.
      operationId: deleteUser
      parameters:
        - name: userId
          in: path
          description: O Id que precisa de ser apagado
          required: true
          schema:
            type: string
      responses:
        '400':
          description: Invalido Id fornecido
        '404':
          description: Utilizador não encontrado
        '200':
          description: Utilizador eliminado com sucesso
  /pecas:
    post:
      tags:
        - pecas
      summary: Criar uma nova lista de peças
      description: Criar uma nova lista de peças para um drone de ID específico.
      operationId: createPecas
      requestBody:
        description: Lista de Peças Criada.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pecas'
          application/xml:
            schema:
              $ref: '#/components/schemas/Pecas'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Pecas'
        required: true
      responses:
        '200':
          description: Operação bem sucedida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pecas'
            application/xml:
              schema:
                $ref: '#/components/schemas/Pecas'
        '400':
          description: ID inválido fornecido
        '404':
          description: Drone não encontrado
        '422':
          description: Exceção de validação
  /pecas/{droneId}:
    get:
      tags:
        - pecas
      summary: Encontra as peças pelo ID do Drone
      description: Inserir o ID para encontrar as peças de um Drone
      operationId: getPecasbyId
      parameters:
        - name: droneId
          in: path
          description: ID do drone
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Operação bem sucedida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pecas'
            application/xml:
              schema:
                $ref: '#/components/schemas/Pecas'
        '400':
          description: ID inválido fornecido
        '404':
          description: Drone não encontrado
    patch:
      tags:
        - pecas
      summary: Atualizar as peças de um drone pelo ID
      description: Atualizar as peças de um drone existente pelo ID
      operationId: updatePecas
      parameters:
        - name: droneId
          in: path
          description: ID do drone que precisa ser alterado
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Atualizar um drone existente
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pecas'
          application/xml:
            schema:
              $ref: '#/components/schemas/Pecas'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Pecas'
        required: true
      responses:
        '200':
          description: Operação bem sucedida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pecas'
            application/xml:
              schema:
                $ref: '#/components/schemas/Pecas'
        '400':
          description: ID inválido fornecido
        '404':
          description: Drone não encontrado
        '422':
          description: Exceção de validação
    delete:
      tags:
        - pecas
      summary: Eliminar as peças de um drone pelo ID
      description: Elimina as peças de um drone pelo seu ID
      operationId: deletePecas
      parameters:
        - name: droneId
          in: path
          description: ID do drone a ser eliminado
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '400':
          description: Número de ID do Drone inválido
        '200':
          description: Peças do drone com ID eliminado com sucesso
  /drone:
    post:
      tags:
        - drone
      summary: Adicionar um novo drone
      description: Adicionar um novo drone
      operationId: addDrone
      requestBody:
        description: Criar um novo drone
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Drone'
          application/xml:
            schema:
              $ref: '#/components/schemas/Drone'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Drone'
        required: true
      responses:
        '200':
          description: Operação bem sucedida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Drone'
            application/xml:
              schema:
                $ref: '#/components/schemas/Drone'
        '400':
          description: Entrada inválida
        '422':
          description: Exceção de validação
    get:
      tags:
        - drone
      summary: Consultar todos os drones
      description: Consulta todos os drones disponíveis atualmente.
      operationId: findAllDrones
      responses:
        '200':
          description: Operação bem-sucedida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Drone'
            application/xml:
              schema:
                $ref: '#/components/schemas/Drone'
        '400':
          description: Erro ao processar a solicitação
  /drone/{droneId}:
    get:
      tags:
        - drone
      summary: Encontra o Drone por ID
      description: Inserir o ID para encontrar o Drone
      operationId: getDroneById
      parameters:
        - name: droneId
          in: path
          description: ID do drone
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Operação bem sucedida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Drone'
            application/xml:
              schema:
                $ref: '#/components/schemas/Drone'
        '400':
          description: ID inválido fornecido
        '404':
          description: Drone não encontrado
    patch:
      tags:
        - drone
      summary: Atualizar um drone por ID
      description: Atualizar um drone existente por ID
      operationId: updateDrone
      parameters:
        - name: droneId
          in: path
          description: ID do drone que precisa ser alterado
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Atualizar um drone existente
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Drone'
          application/xml:
            schema:
              $ref: '#/components/schemas/Drone'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Drone'
        required: true
      responses:
        '200':
          description: Operação bem sucedida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Drone'
            application/xml:
              schema:
                $ref: '#/components/schemas/Drone'
        '400':
          description: ID inválido fornecido
        '404':
          description: Drone não encontrado
        '422':
          description: Exceção de validação
    delete:
      tags:
        - drone
      summary: Eliminar um drone por ID
      description: Elimina um drone
      operationId: deleteDrone
      parameters:
        - name: droneId
          in: path
          description: ID do drone a ser eliminado
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '400':
          description: Número Id do Drone inválido
        '200':
          description: Drone com ID eliminado com sucesso
  /estatisticas/modelos:
    get:
      tags:
        - estatisticas
      summary: Consultar estatísticas dos modelos de drone mais montados
      description: Retorna uma lista dos 10 modelos de drone mais montados. O parâmetro 'limit' permite mudar o limite de resultados retornados.
      operationId: getTopModelsStatistics
      parameters:
        - name: limit
          in: query
          description: Número máximo de resultados a retornar
          required: false
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: Operação bem sucedida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EstatisticaModelo'
            application/xml:
              schema:
                $ref: '#/components/schemas/EstatisticaModelo'
        '400':
          description: Parâmetro inválido
  /estatisticas/pecas:
    get:
      tags:
        - estatisticas
      summary: Consultar estatísticas das peças mais usadas
      description: Retorna uma lista das peças mais usadas em montagens de drones. O parâmetro 'limit' permite mudar o limite de resultados retornados.
      operationId: getTopPartsStatistics
      parameters:
        - name: limit
          in: query
          description: Número máximo de resultados a retornar
          required: false
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: Operação bem sucedida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EstatisticaPeca'
            application/xml:
              schema:
                $ref: '#/components/schemas/EstatisticaPeca'
        '400':
          description: Parâmetro inválido

components:
  schemas:
    Drone:
      type: object
      required:
        - id
        - droneModelo
        - dataMontagem
      properties:
        id:
          type: integer
          format: int64
          example: 1
          description: ID único da montagem do drone
        droneModelo:
          type: string
          example: DJI Mini 4 Pro
        dataMontagem:
          type: string
          format: date
          description: Data de montagem do drone
    Pecas:
      type: object
      required:
        - droneId
        - pecas
      properties:
        droneId:
          type: integer
          format: int64
          example: 1
          description: ID único do drone
        pecas:
          type: array
          items: 
            example: ["motores", "hélices", "baterias"]
            type: string
    User:
      type: object
      required:
        - userId
        - userName
        - email
        - password
        - phone
      properties:
        userId:
          type: integer
          format: int64
          example: 10
        userName:
          type: string
          example: John Rivers
        email:
          type: string
          example: john@email.com
        password:
          type: string
          example: '12345'
        phone:
          type: string
          example: '12345'
      xml:
        name: user
    EstatisticaModelo:
      type: array
      items:
        type: object
        properties:
          modelo:
            type: string
            description: Nome do modelo de drone.
            example: DJI Mini 4 Pro
          quantidade:
            type: integer
            description: Quantidade de vezes que o modelo foi montado.
            example: 25
    EstatisticaPeca:
      type: array
      items:
        type: object
        properties:
          peca:
            type: string
            description: Nome da peça.
            example: motores
          quantidade:
            type: integer
            description: Quantidade de vezes que a peça foi usada em montagens de drones.
            example: 50
    